### ISSUE TITLE
php artisan vendor:publish delatbabel/elocryptfive  Not Working

### ISSUE THREAD

**Issue by adnanmayo** [delatbabel/elocryptfive#16]
Hello i am Trying to publish the config files.  but this is not working..

**Comment by delatbabel** [comment]
Should be working now with the latest tagged version.

The correct command is:

```
php artisan vendor:publish --provider=Delatbabel\Elocrypt\ElocryptServiceProvider
```

**Comment by stuartcusackie** [comment]
Nope. This isn't working for me on Laravel 5.2:
php artisan vendor:publish --provider=Delatbabel\Elocrypt\ElocryptServiceProvider
Nothing to publish for tag [].
Also tried
php artisan vendor:publish --provider=Delatbabel\Elocrypt\ElocryptServiceProvider --tag="config"
Nothing to publish for tag [config].

**Comment by delatbabel** [comment]
OK I can confirm that it works for me.

If it's not working for you then check the following:
- Have you included `Delatbabel\Elocrypt\ElocryptServiceProvider::class` in your `providers` array in `config/app.php`?
- Does the `config/elocrypt.php` file already exist? `php artisan vendor:publish` will only work once, it won't overwrite the file if it already exists in case you have made changes. If you want to force it to overwrite then use the `--force` flag.
- Do you have the latest package? `composer update` just to check.

**Comment by stuartcusackie** [comment]
Hi. Thanks for replying. I have done the following:
- included Delatbabel\Elocrypt\ElocryptServiceProvider::class in providers array
- confirmed that config/elocrypt.php does not exist
- ran composer update

I am still getting the **nothing to publish for tag[]** message when running `php artisan vendor:publish --provider=Delatbabel\Elocrypt\ElocryptServiceProvider`.

Anyway, my client has decided not to go with encryption so I won't be able to look any deeper into this at the moment. Thanks for your help anyway.
